import mongoose from "mongoose";

const postSchema = mongoose.Schema({
    postedBy:{
        type:mongoose.Schema.Types.ObjectId, //this is id which auto generated by mongoose
        ref:"User",
        required:true,
    },

    text:{
        type:String,
        maxLength:500,
    },

    img:{
        type:String,
    },

    likes:{
        // array of user ids  then to count likes we use array.length
        type:[mongoose.Schema.Types.ObjectId],  //type is ObjectId type and ref by User
        ref:"User",
        default:[],

    },

    replies:[ // we need username and userPic and userId and its comment so we did this
        {
            userId:{ //we can know who comment did this
                type:mongoose.Schema.Types.ObjectId,
                ref:"User",
                required:true,
            },
             text:{
                type:String,
                required:true,
                maxLength:500,
            },
            userProfilePic:{
                type:String,
            },
            username:{
                type:String,
            }
        },
    ]

},{timestamps:true}

);


const Post = mongoose.model("Post",postSchema);


export default Post;